name: photo_view
description: Photo View provides a gesture sensitive zoomable widget. Photo View is largely used to show interacive images and other stuff such as SVG.
version: 0.10.3
homepage: https://github.com/renancaraujo/photo_view

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.6.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter

flutter:
