name: photo_view
description: Photo View provides a gesture sensitive zoomable widget. PhotoView is largely used to show interacive images.
version: 0.4.1
author: Renan C. Ara√∫jo <renan@caraujo.me>
homepage: https://github.com/renancaraujo/photo_view

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.9-pre.94 <2.0.0"

dependencies:
  after_layout: ^1.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter

flutter:
